""" Building block for crawling S3 CSVs for further use in Athena """

from constructs import Construct
from aws_cdk import (
    aws_s3 as s3,
    aws_glue as glue,
    aws_iam as iam,
    Aws,
)


class GlueCrawlerService(Construct):
    """ Crawl CSVs in S3 bucket generated from RDS using Glue Crawler """
    def __init__(self, scope: Construct, id: str,
                 target_bucket_arn: str,
                ):
        """
        Parameters:
        target_bucket_arn (str): ARN of S3 bucket that contains CSVs.
        Notes:
        * Should get S3 bucket ARN instead of it's instance, otherwise it will be a cyclic reference.
        """
        super().__init__(scope, id)


        # S3 bucket that glue crawler is going to crawl
        target_bucket = s3.Bucket.from_bucket_arn(
            self,
            'CrawlerTargetBucketFromArn',
            target_bucket_arn,
        )

        s3_access_statement = iam.PolicyStatement(
            actions=['s3:*'],
            resources=[
                target_bucket.bucket_arn,
                f'{target_bucket.bucket_arn}/*',
            ],
        )

        glue_role = iam.Role(
            self,
            'airbnb-glue-role',
            assumed_by=iam.ServicePrincipal('glue.amazonaws.com'),
            inline_policies = [
                iam.PolicyDocument(statements=[s3_access_statement]),
            ],
            managed_policies=[
                iam.ManagedPolicy.from_managed_policy_arn(
                    self,
                    'gluemanagedpolicy',
                    managed_policy_arn='arn:aws:iam::aws:policy/service-role/AWSGlueServiceRole'
                ),
            ],
        )

        glue_database = glue.CfnDatabase(
            self,
            'glue-database',
            catalog_id=Aws.ACCOUNT_ID,
            database_input = glue.CfnDatabase.DatabaseInputProperty(
                name='airbnbgluedb',
                description='Glue Database for Airbnb data extracted from RDS',
                create_table_default_permissions=[
                    glue.CfnDatabase.PrincipalPrivilegesProperty(
                        permissions=['ALL'],
                        principal=glue.CfnDatabase.DataLakePrincipalProperty(
                            data_lake_principal_identifier='EVERYONE',
                        )
                    )
                ],
            )
        )

        s3_targets = glue.CfnCrawler.S3TargetProperty(
            path=f'{target_bucket.bucket_name}/rds_result/'
        )

        """ crawler = glue.CfnCrawler(
            self,
            'crawler',
            description='Crawl listings CSV related to Airbnb project generated by Aws DataBrew from RDS.',
            database_name=glue_database.database_input.name,
            role=glue_role.role_arn,
            targets = glue.CfnCrawler.TargetsProperty(s3_targets=[s3_targets])
        ) """
